"""Engine for generating, validating and rating daily logic puzzles."""

from .board import MAX_SIZE, MIN_SIZE, Board, BoardError, PuzzleType
from .deduce import (
    DEFAULT_GUESS_CAP,
    DeductionError,
    DeductionStep,
    DeductionTrace,
    ForcedMove,
    deduce,
    first_forced_move,
)
from .difficulty import (
    GUESSING_FLOOR,
    LEVEL_NAMES,
    RULE_WEIGHTS,
    SCORE_BANDS,
    Difficulty,
    score_difficulty,
)
from .generator import (
    DEFAULT_ATTEMPTS,
    DEFAULT_SIZE,
    MAX_GENERATABLE_SIZE,
    MIN_GENERATABLE_SIZE,
    GenerationConfig,
    GenerationError,
    generate_puzzle,
    verify_replay,
)
from .prng import Prng
from .puzzle import (
    JsonValue,
    Puzzle,
    PuzzleParseError,
    canonical_dumps,
    dumps_puzzle,
    load_puzzle,
    parse_puzzle,
    puzzle_to_dict,
)
from .ramp import (
    MAX_LEVEL,
    MIN_LEVEL,
    RAMP_ATTEMPTS,
    RAMP_START,
    RAMP_TYPE,
    WEEKLY_RAMP,
    DifficultyTarget,
    RampedPuzzle,
    generate_ramped,
    target_for,
)
from .render import render_board, render_puzzle
from .rulebook import (
    STAR_BATTLE_SIZE,
    STAR_BATTLE_STARS,
    MarkRulebook,
    Rulebook,
    RulebookError,
    puzzle_id,
    rulebook_for,
    rulebooks,
    split_puzzle_id,
)
from .solver import (
    DEFAULT_LIMIT,
    SolverError,
    count_solutions,
    format_solution,
    has_unique_solution,
    iter_solutions,
)

__all__ = [
    "DEFAULT_ATTEMPTS",
    "DEFAULT_GUESS_CAP",
    "DEFAULT_LIMIT",
    "DEFAULT_SIZE",
    "GUESSING_FLOOR",
    "LEVEL_NAMES",
    "MAX_GENERATABLE_SIZE",
    "MAX_LEVEL",
    "MAX_SIZE",
    "MIN_GENERATABLE_SIZE",
    "MIN_LEVEL",
    "MIN_SIZE",
    "RAMP_ATTEMPTS",
    "RAMP_START",
    "RAMP_TYPE",
    "RULE_WEIGHTS",
    "SCORE_BANDS",
    "STAR_BATTLE_SIZE",
    "STAR_BATTLE_STARS",
    "WEEKLY_RAMP",
    "Board",
    "BoardError",
    "DeductionError",
    "DeductionStep",
    "DeductionTrace",
    "Difficulty",
    "DifficultyTarget",
    "ForcedMove",
    "GenerationConfig",
    "GenerationError",
    "JsonValue",
    "MarkRulebook",
    "Prng",
    "Puzzle",
    "PuzzleParseError",
    "PuzzleType",
    "RampedPuzzle",
    "Rulebook",
    "RulebookError",
    "SolverError",
    "canonical_dumps",
    "count_solutions",
    "deduce",
    "dumps_puzzle",
    "first_forced_move",
    "format_solution",
    "generate_puzzle",
    "generate_ramped",
    "has_unique_solution",
    "iter_solutions",
    "load_puzzle",
    "parse_puzzle",
    "puzzle_id",
    "puzzle_to_dict",
    "render_board",
    "render_puzzle",
    "rulebook_for",
    "rulebooks",
    "score_difficulty",
    "split_puzzle_id",
    "target_for",
    "verify_replay",
]
